MATPLOTLIB_MODULE_DEBUG: set_latest_plot_data CALLED with data. Title: 'V_CE (V)'
GUI: open_matplotlib_plot_callback triggered
GUI: About to start Matplotlib thread.
MATPLOTLIB_MODULE_DEBUG: plot_with_matplotlib_actual checking _shared_plot_data. Is None? False
GUI: Matplotlib thread started.
C:\Users\kenur\PycharmProjects\PhysicsDataPlot\app\matplotlib.py:36: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure()
Matplotlib module: Showing plot...
C:\Users\kenur\PycharmProjects\PhysicsDataPlot\app\matplotlib.py:50: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.show()
Matplotlib module: Plot window closed.
GUI: open_matplotlib_plot_callback triggered
GUI: About to start Matplotlib thread.
MATPLOTLIB_MODULE_DEBUG: plot_with_matplotlib_actual checking _shared_plot_data. Is None? False
GUI: Matplotlib thread started.
Matplotlib module: Showing plot...
Matplotlib module: Plot window closed.
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001FA8D44AE80>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4101, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001FA8D44AE80>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4101, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001FA8D3D87C0>
Traceback (most recent call last):
  File "C:\Users\kenur\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
